// ── Expected sheets & columns ─────────────────────────────────
export const EXPECTED_SHEETS = {
  'GL Transactions': { role:'primary',   required:true,  desc:'Core transaction data' },
  'COA Concept':     { role:'reference', required:false, desc:'Brand / division concepts' },
  'COA CC':          { role:'reference', required:false, desc:'Cost centre master' },
  'COA Acc':         { role:'reference', required:false, desc:'GL account master' },
  'COA IC':          { role:'reference', required:false, desc:'Intercompany codes' },
  'ICC':             { role:'reference', required:false, desc:'IC approved combinations' },
  'Reporting':       { role:'reference', required:false, desc:'Reporting segment codes' },
};
export const EXPECTED_COLS = [
  'TERRITORY','LEDGER NAME','SOURCE','CATEGORY','GL DATE','JV VOUCHER NUMBER',
  'JV NAME','SUBLEDGER JV NUMBER','VENDOR CUSTOMER NAME','VENDOR CUSTOMER NUMBER',
  'TRANSACTION TYPE','TRANSACTION NUMBER','GL CREATION DATE','ENTITY CODE',
  'CONCEPT CODE','COST CENTRE CODE','GL ACCOUNT CODE','GL DESC','INTER COMPANY CODE',
  'INTER CONCEPT CODE','REPORTING CODE','CONCATENATED GCC SEGMENTS','CURRENCY CODE',
  'ENTERED DR','ENTERED CR','ACCOUNTED DR','ACCOUNTED CR','DESCRIPTION',
  'ATTRIBUTE1','ATTRIBUTE2','ATTRIBUTE3','ATTRIBUTE4','ATTRIBUTE5','ATTRIBUTE6',
  'ATTRIBUTE7','ATTRIBUTE8','ATTRIBUTE9','ATTRIBUTE10','ATTRIBUTE11','ATTRIBUTE12',
  'ATTRIBUTE13','ATTRIBUTE14','ATTRIBUTE15','ATTRIBUTE16','ATTRIBUTE19','USERS','NET AMOUNT',
];
export const PREVIEW_COLS = [
  'GL DATE','JV VOUCHER NUMBER','SOURCE','ENTITY CODE','CONCEPT CODE',
  'COST CENTRE CODE','GL ACCOUNT CODE','GL DESC',
  'ENTERED DR','ENTERED CR','NET AMOUNT','CURRENCY CODE','DESCRIPTION','USERS',
];

// ── Shortlisted HIGH-RISK GL codes (81 accounts) ──────────────
export const SHORTLISTED_GL = new Set([
  11131,11132,11251,11252,11253,11254,11256,11258,
  12104,12405,12504,12505,12507,12701,12802,
  14199,14501,14504,14551,14552,14554,
  16205,16208,16306,16307,16309,
  21101,22208,23224,24109,
  24302,24303,24304,24305,24308,24312,24313,24315,24316,
  24318,24319,24320,24324,24333,24334,24351,24352,24353,
  24354,24355,24358,24359,24365,24366,24368,24704,24803,24903,
  41202,42105,42106,42301,42305,42306,
  52105,52106,
  55101,55102,55104,55113,
  61104,61111,61115,61122,64315,71506,
  92001,99108,99111,99112,99202,
]);

// ── Expired / dummy / pending ─────────────────────────────────
export const EXPIRED_ACCOUNTS = { 14451:'2025-12-15', 24308:'2025-04-30', 24831:'2025-11-13' };
export const EXPIRED_CC       = { 56251:'2026-01-26' };
export const DUMMY_ACCOUNTS   = new Set([92001]);
export const PENDING_ACCOUNTS = new Set([11131,11132,14554,42105,42106,52105,52106]);

// ── ACCOUNT META ─────────────────────────────────────────────
// type drives:  (a) which periodic rules apply
//               (b) which transaction rules apply when drilling down
// txRules = transaction rule IDs from engine.js that are relevant for this account type
export const ACCOUNT_META = {
  // ── DUMMY ───────────────────────────────────────────────────
  92001:{ label:'Dummy Account',              type:'DUMMY',    category:'Dummy / Unknown Accounts',       txRules:['DUM-01','SOD-01','SOD-02','TIME-01','TIME-02','JQ-01','DUP-01'] },
  // ── PENDING / UNKNOWN ───────────────────────────────────────
  11131:{ label:'Unknown Asset Account',      type:'PENDING',  category:'Dummy / Unknown Accounts',       txRules:['PEND','SOD-01','TIME-01','TIME-02','JQ-01'] },
  11132:{ label:'Unknown Asset Account',      type:'PENDING',  category:'Dummy / Unknown Accounts',       txRules:['PEND','SOD-01','TIME-01','TIME-02','JQ-01'] },
  14554:{ label:'Unknown Cash Account',       type:'PENDING',  category:'Dummy / Unknown Accounts',       txRules:['PEND','SOD-01','TIME-01','TIME-02','JQ-01'] },
  42105:{ label:'Unknown Revenue Account',    type:'PENDING',  category:'Dummy / Unknown Accounts',       txRules:['PEND','SOD-01','TIME-01','TIME-02','JQ-01'] },
  42106:{ label:'Unknown Revenue Account',    type:'PENDING',  category:'Dummy / Unknown Accounts',       txRules:['PEND','SOD-01','TIME-01','TIME-02','JQ-01'] },
  52105:{ label:'Unknown Expense Account',    type:'PENDING',  category:'Dummy / Unknown Accounts',       txRules:['PEND','SOD-01','TIME-01','TIME-02','JQ-01'] },
  52106:{ label:'Unknown Expense Account',    type:'PENDING',  category:'Dummy / Unknown Accounts',       txRules:['PEND','SOD-01','TIME-01','TIME-02','JQ-01'] },
  // ── CLEARING ────────────────────────────────────────────────
  14551:{ label:'Cash Clearing',              type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-01','CLR-02','SOD-01','TIME-01','TIME-02','TIME-03'] },
  14552:{ label:'Card Clearing',              type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-01','CLR-02','SOD-01','TIME-01','TIME-02','TIME-03'] },
  16205:{ label:'Capex Clearing',             type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-02','SOD-01','SOD-02','TIME-01','TIME-02'] },
  16208:{ label:'Capex Clearing',             type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-02','SOD-01','SOD-02','TIME-01','TIME-02'] },
  22208:{ label:'AP Clearing',                type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-02','SOD-01','TIME-01','TIME-02'] },
  99108:{ label:'Suspense Account',           type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-02','SOD-01','SOD-02','JQ-01','TIME-01','TIME-02'] },
  99111:{ label:'COD Clearing',               type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-01','CLR-02','SOD-01','TIME-01','TIME-02'] },
  99112:{ label:'CP Clearing',                type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-01','CLR-02','SOD-01','TIME-01','TIME-02'] },
  99202:{ label:'Misc Clearing',              type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-02','SOD-01','SOD-02','JQ-01','TIME-01','TIME-02'] },
  24803:{ label:'Accrued Clearing',           type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-02','SOD-01','TIME-01','TIME-02'] },
  24903:{ label:'Accrued Clearing',           type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-02','SOD-01','TIME-01','TIME-02'] },
  // ── PROVISIONS — Balance Sheet ───────────────────────────────
  11251:{ label:'Inventory Provision BS',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  11252:{ label:'Inventory Provision BS',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  11253:{ label:'Inventory Provision BS',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  11254:{ label:'Inventory Provision BS',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  11256:{ label:'Inventory Provision BS',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  11258:{ label:'Inventory Provision BS',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  12405:{ label:'Provision for Receivables',  type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  // ── PROVISIONS — HR / Payroll ────────────────────────────────
  24351:{ label:'Leave Encashment Provision', type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24352:{ label:'Annual Leave Provision',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24353:{ label:'Gratuity Provision',         type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24354:{ label:'Salary Provision',           type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24355:{ label:'Bonus Provision',            type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24358:{ label:'Other HR Provision',         type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24359:{ label:'Payroll Provision',          type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24365:{ label:'Cashier Provision',          type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24366:{ label:'Other Payroll Provision',    type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  // ── PROVISIONS — Opex / Accruals ────────────────────────────
  24302:{ label:'Rent Accrual',               type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24303:{ label:'Utilities Accrual',          type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24304:{ label:'Marketing Accrual',          type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24305:{ label:'Maintenance Accrual',        type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24308:{ label:'Other Accrual (Expired)',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','SEG-01','JQ-01','TIME-03'] },
  24312:{ label:'Service Charge Accrual',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24313:{ label:'IT Accrual',                 type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24315:{ label:'Insurance Accrual',          type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24316:{ label:'Security Accrual',           type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24318:{ label:'Legal Accrual',              type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24319:{ label:'Consultancy Accrual',        type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24320:{ label:'Other Opex Accrual',         type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24324:{ label:'Staff Welfare Accrual',      type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24333:{ label:'Franchise Fee Accrual',      type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24334:{ label:'Royalty Accrual',            type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24368:{ label:'Sundry Accrual',             type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  24704:{ label:'Long-Term Provision',        type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  // ── PROVISIONS — Inventory P&L ──────────────────────────────
  55101:{ label:'Inventory Provision PL',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  55102:{ label:'Inventory Write-down',       type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  55104:{ label:'Inventory Shrinkage',        type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  55113:{ label:'Inventory Obsolescence',     type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  // ── EMPLOYEE ADVANCES ────────────────────────────────────────
  12504:{ label:'Employee Cash Advance',      type:'ADVANCE',  category:'Employee Advances & Discounts',  txRules:['EMP-01','EMP-02','SOD-01','SOD-02','TIME-01','TIME-02','JQ-01'] },
  12505:{ label:'Employee Loan',              type:'ADVANCE',  category:'Employee Advances & Discounts',  txRules:['EMP-01','EMP-02','SOD-01','SOD-02','TIME-01','TIME-02','JQ-01'] },
  12507:{ label:'Staff Advance',              type:'ADVANCE',  category:'Employee Advances & Discounts',  txRules:['EMP-01','EMP-02','SOD-01','SOD-02','TIME-01','TIME-02','JQ-01'] },
  42305:{ label:'Employee Discount Expense',  type:'ADVANCE',  category:'Employee Advances & Discounts',  txRules:['EMP-03','SOD-01','TIME-01','TIME-02'] },
  42306:{ label:'Employee Discount VAT',      type:'ADVANCE',  category:'Employee Advances & Discounts',  txRules:['EMP-03','SOD-01','TIME-01','TIME-02'] },
  // ── CASH ────────────────────────────────────────────────────
  14501:{ label:'Petty Cash',                 type:'CASH',     category:'Cash & Petty Cash',              txRules:['SOD-01','TIME-01','TIME-02','JQ-01','DUP-01'] },
  14504:{ label:'Petty Cash',                 type:'CASH',     category:'Cash & Petty Cash',              txRules:['SOD-01','TIME-01','TIME-02','JQ-01','DUP-01'] },
  61104:{ label:'Cashier Allowance',          type:'CASH',     category:'Cash & Petty Cash',              txRules:['SOD-01','TIME-01','TIME-02','JQ-01'] },
  61111:{ label:'Cash Handling Expense',      type:'CASH',     category:'Cash & Petty Cash',              txRules:['SOD-01','TIME-01','TIME-02','JQ-01'] },
  64315:{ label:'Cash Difference',            type:'CASH',     category:'Cash & Petty Cash',              txRules:['SOD-01','TIME-01','TIME-02','JQ-01','DUP-01'] },
  // ── CWIP ─────────────────────────────────────────────────────
  16306:{ label:'CWIP — Fit-out',             type:'CWIP',     category:'Capital Work in Progress',       txRules:['CWIP-01','CWIP-02','JQ-01','SOD-01','SOD-02'] },
  16307:{ label:'CWIP — Equipment',           type:'CWIP',     category:'Capital Work in Progress',       txRules:['CWIP-01','CWIP-02','JQ-01','SOD-01','SOD-02'] },
  16309:{ label:'CWIP — IT',                  type:'CWIP',     category:'Capital Work in Progress',       txRules:['CWIP-01','CWIP-02','JQ-01','SOD-01','SOD-02'] },
  // ── INTERCOMPANY ─────────────────────────────────────────────
  12701:{ label:'IC Receivable',              type:'IC',       category:'Inter-company',                  txRules:['IC-01','SOD-02','TIME-03','JQ-01'] },
  21101:{ label:'IC Payable',                 type:'IC',       category:'Inter-company',                  txRules:['IC-01','SOD-02','TIME-03','JQ-01'] },
  // ── LOYALTY / GV ─────────────────────────────────────────────
  23224:{ label:'Shukran Gift Card Liability',type:'LOYALTY',  category:'Gift Vouchers & Loyalty',        txRules:['GV-01','GV-02','SOD-01','SOD-02','TIME-01','TIME-02'] },
  12104:{ label:'GV Receivable',              type:'LOYALTY',  category:'Gift Vouchers & Loyalty',        txRules:['GV-02','SOD-01','SOD-02','TIME-01','TIME-02'] },
  71506:{ label:'GV Expense',                 type:'LOYALTY',  category:'Gift Vouchers & Loyalty',        txRules:['GV-02','SOD-01','JQ-01','TIME-01','TIME-02'] },
  // ── ACCRUED LIABILITIES ──────────────────────────────────────
  12802:{ label:'Prepayments',                type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','JQ-01','TIME-03','SOD-01'] },
  24109:{ label:'Accrued Liabilities',        type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','PROV-03','JQ-01','TIME-03','SOD-01'] },
  // ── SALES / REVENUE ──────────────────────────────────────────
  41202:{ label:'Sales Returns',              type:'REVENUE',  category:'Sales & Discounts',              txRules:['SOD-01','SOD-02','TIME-01','TIME-02','JQ-01','DUP-01'] },
  42301:{ label:'Sales Discount',             type:'REVENUE',  category:'Sales & Discounts',              txRules:['SOD-01','SOD-02','TIME-01','TIME-02','JQ-01','DUP-01'] },
  // ── INVENTORY RECEIVING ──────────────────────────────────────
  14199:{ label:'Inventory Receiving (GR/IR)',type:'CLEARING', category:'Clearing & Suspense',            txRules:['CLR-02','SOD-01','TIME-01','TIME-02'] },
  // ── PAYROLL ──────────────────────────────────────────────────
  61115:{ label:'Leave Encashment',           type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','JQ-01','TIME-03','SOD-01'] },
  61122:{ label:'Gratuity Expense',           type:'PROVISION',category:'Provision Accounts',             txRules:['PROV-01','PROV-02','JQ-01','TIME-03','SOD-01'] },
};

// ── Default config ─────────────────────────────────────────────
export const DEFAULT_CONFIG = {
  clearingWindowDays:        7,
  cwipAgeingDays:            180,
  roundNumberThreshold:      1000,
  postingLagDays:            3,
  duplicateWindowDays:       30,
  employeeAdvanceLimit:      500,
  advanceRecoveryDays:       90,
  highValueManualThreshold:  10000,
  provisionConcentrationPct: 60,
  blankDescMinAmount:        1000,
  capitalizationThreshold:   500,
  businessHoursStart:        8,
  businessHoursEnd:          20,
  weekendDays:               [5,6],
  approvalThresholds:        [500, 1000, 10000, 100000],
  thresholdBandPct:          10,
  vendorDormancyMonths:      8,
  enabledRules: {
    'CLR-02':true,'GV-02':true,
    'PROV-01':true,'PROV-02':true,'PROV-03':true,
    'EMP-01':true,'EMP-02':true,'EMP-03':true,
    'SOD-01':true,'SOD-02':true,
    'TIME-01':true,'TIME-02':true,'TIME-03':true,'TIME-04':true,
    'DUP-01':true,'JQ-01':true,'CWIP-01':true,'CWIP-02':true,
    'DEF-01':true,'THR-01':true,'VND-01':true,'VND-02':true,
  },
  anomalyThreshold: 0.65,
  anomalyVoteCount: 3,
  anomalyContamination: 0.08,
  anomalyIncludeRuleFlagsInMl: true,
  /** Per sklearn model wall time (seconds); 0 disables timeout and runs models to completion. */
  anomalyModelTimeoutSeconds: 0,
  /**
   * Which anomaly detectors to run (API subset). Empty = all five.
   * @type {string[]}
   */
  anomalyActiveModels: [
    'isolation_forest',
    'pca_reconstruction',
    'dbscan',
    'lof',
    'knn_distance',
  ],
};

/** Options for Configure → ML models (IDs match FastAPI `active_anomaly_models`). */
export const ANOMALY_MODEL_OPTIONS = [
  { id: 'isolation_forest', label: 'Isolation Forest', hint: 'Global outlier scores from random partition trees.' },
  { id: 'pca_reconstruction', label: 'PCA reconstruction', hint: 'High reconstruction error → unusual in PCA space.' },
  { id: 'dbscan', label: 'DBSCAN', hint: 'Noise points (label −1) treated as outliers.' },
  { id: 'lof', label: 'Local Outlier Factor', hint: 'Density-based; good for local anomalies.' },
  { id: 'knn_distance', label: 'KNN distance', hint: 'Mean distance to k neighbours in scaled space.' },
];

export const SEV = { CRITICAL:'CRITICAL', HIGH:'HIGH', MEDIUM:'MEDIUM' };
export const CAT = {
  DUMMY:'Dummy / Unknown Accounts', SEGMENT:'Segment Validity',
  CLEARING:'Clearing & Suspense',   PROVISION:'Provision Accounts',
  EMPLOYEE:'Employee Advances & Discounts', GV:'Gift Vouchers & Loyalty',
  IC:'Inter-company',               CWIP:'Capital Work in Progress',
  SOD:'Segregation of Duties',      TIMING:'Posting Timing',
  JOURNAL:'Journal Quality',        DUPLICATE:'Duplicate Detection',
};
export const STEPS = [
  { id:1, label:'Upload' },
  { id:2, label:'Configure' },
  { id:3, label:'Analyse' },
  { id:4, label:'Findings' },
];

// ── Transaction rule → display label ──────────────────────────
export const TX_RULE_LABELS = {
  'DUM-01':'Dummy account posting','PEND':'Pending/unknown account',
  'SEG-01':'Expired GL account','SEG-02':'Expired cost centre','SEG-03':'Orphan GL account',
  'CLR-01':'Manual to clearing','CLR-02':'Uncleared clearing balance',
  'PROV-01':'Period-end concentration','PROV-02':'Duplicate provision','PROV-03':'Round number provision',
  'EMP-01':'Advance over limit','EMP-02':'Advance — no recovery','EMP-03':'Discount — missing tax',
  'GV-01':'Manual to Shukran','GV-02':'Loyalty liability release',
  'IC-01':'One-sided IC entry',
  'CWIP-01':'CWIP ageing overdue','CWIP-02':'CWIP below threshold',
  'SOD-01':'SoD violation','SOD-02':'High-value — no approval',
  'TIME-01':'After-hours posting','TIME-02':'Weekend posting',
  'TIME-03':'Backdated — prior period','TIME-04':'Delayed posting',
  'DUP-01':'Duplicate posting','JQ-01':'Blank description',
};

// ── Audit Protocol cards (Configure page) ─────────────────────
export const AUDIT_PROTOCOLS = [
  { id:'DUM-01', label:'Dummy Account Posting', status:'LOCKED', sev:'CRITICAL',
    objective:'Flag every transaction posted to account 92001. No description, no known purpose, no authorised use.',
    algorithm:`IF (GL_ACCOUNT_CODE == 92001)\nTHEN severity = 'CRITICAL'\n-- No exceptions, no threshold, no source filter.`,
    impact:'Highest-priority flag. May indicate migration artifacts, test postings, or active transaction parking.',
    configField:null },
  { id:'PEND-01', label:'Pending / Unknown Account Posting', status:'LOCKED', sev:'CRITICAL',
    objective:'Flag every transaction to seven accounts with no description and no known business purpose.',
    algorithm:`IF (GL_ACCOUNT_CODE IN (11131,11132,14554,\n  42105,42106,52105,52106))\nTHEN severity = 'CRITICAL'`,
    impact:'Unknown accounts adjacent to cash, revenue, and expense series represent significant control gaps.',
    configField:null },
  { id:'CLR-01', label:'Manual Journal to Cash Clearing', status:'LOCKED', sev:'CRITICAL',
    objective:'Cash clearing accounts should only be fed by automated POS system feeds. Any manual entry bypasses all clearing controls.',
    algorithm:`IF (GL_ACCOUNT_CODE IN (14551, 14552))\n  AND (SOURCE == 'MANUAL')\nTHEN severity = 'CRITICAL'`,
    impact:'Every manual clearing entry needs a documented business justification and senior approval.',
    configField:null },
  { id:'GV-01', label:'Manual Entry to Shukran Gift Card', status:'LOCKED', sev:'CRITICAL',
    objective:'The Shukran loyalty liability account is owned by the loyalty platform. Manual overrides are a direct integrity risk.',
    algorithm:`IF (GL_ACCOUNT_CODE == 23224)\n  AND (SOURCE == 'MANUAL')\nTHEN severity = 'CRITICAL'`,
    impact:'Can inflate or deflate the loyalty program balance, affecting reported liabilities and customer trust.',
    configField:null },
  { id:'IC-01', label:'One-Sided Intercompany Entry', status:'LOCKED', sev:'CRITICAL',
    objective:'Every IC receivable must have a matching payable in the same JV, and vice versa. One-sided entries break group consolidation.',
    algorithm:`IF (JV has 12701 but NOT 21101)\n  OR (JV has 21101 but NOT 12701)\nTHEN severity = 'CRITICAL'`,
    impact:'One-sided IC entries cause consolidation mismatches requiring manual correction before group sign-off.',
    configField:null },
  { id:'GV-02', label:'Shukran Liability — Unjustified Release', status:'ACTIVE', sev:'CRITICAL',
    objective:'A debit to the Shukran loyalty account without a matching sales or redemption entry. Liability reduced with no business event.',
    algorithm:`IF (GL_ACCOUNT_CODE = 23224 AND ENTERED_DR > 0\n  AND no 4xxxx credit in same JV)\nTHEN severity = 'CRITICAL'`,
    impact:'Releasing a loyalty liability without a redemption event artificially inflates profit.',
    configField:null },
  { id:'CLR-02', label:'Uncleared Clearing Balance', status:'ACTIVE', sev:'HIGH',
    objective:'A debit to cash clearing with no matching credit within the clearing window. Persistent balances indicate unreconciled POS settlements.',
    algorithm:`IF (ENTERED_DR > 0 AND no matching ENTERED_CR\n  within clearingWindowDays)\nTHEN severity = 'HIGH'`,
    impact:'Cash or card receipts recorded but not banked. Each day of ageing increases misappropriation risk.',
    configField:'clearingWindowDays', configLabel:'Clearing window', configSuffix:'days',
    configHint:'Maximum age before an unmatched debit is flagged' },
  { id:'PROV-01', label:'Period-End Provision Concentration', status:'ACTIVE', sev:'HIGH',
    objective:'More than the threshold % of monthly provision bookings concentrated in the last 7 days of the month.',
    algorithm:`IF (last7days / monthTotal > provisionConcentrationPct)\nTHEN severity = 'HIGH'`,
    impact:'Period-end concentration is one of the most reliable indicators of managed earnings.',
    configField:'provisionConcentrationPct', configLabel:'Period-end concentration alert', configSuffix:'%',
    configHint:'Flag if this % of monthly provisions fall in the last 7 days' },
  { id:'PROV-02', label:'Duplicate Provision Entry', status:'ACTIVE', sev:'HIGH',
    objective:'Same provision account, same cost centre, same rounded amount posted more than once in the same calendar month.',
    algorithm:`key = GL_ACCOUNT + CC + ROUND(amount) + MONTH\nIF COUNT(key) > 1 THEN severity = 'HIGH'`,
    impact:'Duplicate provisions directly double-count expenses and overstate liabilities.',
    configField:null },
  { id:'PROV-03', label:'Round Number Provision', status:'ACTIVE', sev:'MEDIUM',
    objective:'Provision amount is an exact multiple of the round number threshold, suggesting estimation rather than calculation.',
    algorithm:`IF (amount % threshold == 0 AND amount >= threshold×5)\nTHEN severity = 'MEDIUM'`,
    impact:'Pattern analysis across months can reveal systematic earnings manipulation.',
    configField:'roundNumberThreshold', configLabel:'Round number threshold', configSuffix:'BHD',
    configHint:'Provisions that are exact multiples of this amount are flagged' },
  { id:'EMP-01', label:'Employee Advance Exceeds Policy Limit', status:'ACTIVE', sev:'HIGH',
    objective:'Advance debit to employee advance accounts exceeding the configured per-advance policy limit without documented approval.',
    algorithm:`IF (ENTERED_DR > employeeAdvanceLimit)\nTHEN severity = 'HIGH'`,
    impact:'May signal fictitious employees or collusion between approver and recipient.',
    configField:'employeeAdvanceLimit', configLabel:'Per-advance policy limit', configSuffix:'BHD',
    configHint:'Advances above this value without approval reference are flagged' },
  { id:'EMP-02', label:'Employee Advance — No Recovery', status:'ACTIVE', sev:'HIGH',
    objective:'Advance debit with no matching recovery credit for the same employee within the recovery period.',
    algorithm:`IF (no credit for same VENDOR_CUSTOMER_NUMBER\n  within advanceRecoveryDays)\nTHEN severity = 'HIGH'`,
    impact:'Ageing advances strongly indicate fictitious advance schemes.',
    configField:'advanceRecoveryDays', configLabel:'Advance recovery period', configSuffix:'days',
    configHint:'Days before an unrecovered advance is flagged' },
  { id:'EMP-03', label:'Employee Discount — Missing Tax', status:'ACTIVE', sev:'HIGH',
    objective:'Employee discount entry (42305) in a JV with no corresponding tax entry (42306).',
    algorithm:`IF (JV has 42305 AND NOT 42306) THEN severity = 'HIGH'`,
    impact:'VAT/tax compliance gap — tax leg missing from discount transaction.',
    configField:null },
  { id:'SOD-01', label:'Segregation of Duties Violation', status:'ACTIVE', sev:'HIGH',
    objective:'Both debit and credit legs of a manual JV posted by the same user. No independent review.',
    algorithm:`IF (SOURCE='MANUAL' AND DISTINCT USERS=1\n  AND JV has DR and CR)\nTHEN severity = 'HIGH'`,
    impact:'Single person can create and post entries without oversight — primary indicator of management fraud.',
    configField:null },
  { id:'SOD-02', label:'High-Value Manual — No Approval Reference', status:'ACTIVE', sev:'HIGH',
    objective:'Manual journal above the high-value threshold with blank or generic DESCRIPTION.',
    algorithm:`IF (SOURCE='MANUAL' AND amount >= threshold\n  AND DESCRIPTION is blank/generic)\nTHEN severity = 'HIGH'`,
    impact:'Cannot be traced to a business event or authorising officer during an audit.',
    configField:'highValueManualThreshold', configLabel:'High-value manual threshold', configSuffix:'BHD',
    configHint:'Manual entries above this value must have a description' },
  { id:'TIME-01', label:'After-Hours Posting', status:'ACTIVE', sev:'HIGH',
    objective:'GL CREATION DATE outside business hours on a manual entry or high-value transaction.',
    algorithm:`IF (hour < start OR hour >= end)\n  AND (MANUAL OR amount >= threshold)\nTHEN severity = 'HIGH'`,
    impact:'System access during unsupervised periods is a key fraud indicator.',
    configField:'businessHoursStart', configLabel:'Business hours', configSuffix:null,
    configHint:'Entries outside start–end window are flagged', configField2:'businessHoursEnd' },
  { id:'TIME-02', label:'Weekend / Holiday Posting', status:'ACTIVE', sev:'HIGH',
    objective:'GL CREATION DATE on a configured weekend day for manual or high-value transactions.',
    algorithm:`IF (day_of_week IN weekendDays)\n  AND (MANUAL OR amount >= threshold)\nTHEN severity = 'HIGH'`,
    impact:'Weekend postings represent unauthorised system access outside normal working hours.',
    configField:'weekendDays', configLabel:'Weekend days (GCC)', configSuffix:null,
    configHint:'Select which days constitute weekends in your jurisdiction' },
  { id:'TIME-03', label:'Backdated Entry — Prior Period', status:'ACTIVE', sev:'HIGH',
    objective:'Entry created in a later calendar month than its GL DATE — posted into a closed period.',
    algorithm:`IF (lag > threshold AND MONTH(GL_DATE) != MONTH(GL_CREATION_DATE))\nTHEN severity = 'HIGH'`,
    impact:'Backdating into closed periods manipulates period-end financial results.',
    configField:'postingLagDays', configLabel:'Posting lag threshold', configSuffix:'days',
    configHint:'Lag above this AND across a month boundary triggers this rule' },
  { id:'TIME-04', label:'Delayed Posting — Same Period', status:'ACTIVE', sev:'MEDIUM',
    objective:'GL CREATION DATE more than the lag threshold after GL DATE, within the same calendar month.',
    algorithm:`IF (lag > threshold AND same month) THEN severity = 'MEDIUM'`,
    impact:'Patterns by user or account can indicate systematic control avoidance.',
    configField:'postingLagDays', configLabel:'Posting lag threshold', configSuffix:'days',
    configHint:'GL → creation date gap above this value is flagged' },
  { id:'DUP-01', label:'Potential Duplicate Posting', status:'ACTIVE', sev:'HIGH',
    objective:'Same GL account, rounded amount, cost centre, and concept code in two different JVs within the duplicate window.',
    algorithm:`key = account|amount|CC|concept\nIF same key in different JV within window\nTHEN severity = 'HIGH'`,
    impact:'Double-counted expenses or inflated liabilities.',
    configField:'duplicateWindowDays', configLabel:'Duplicate detection window', configSuffix:'days',
    configHint:'Look-back window for same account/amount/CC/concept combination' },
  { id:'JQ-01', label:'Blank / Generic Description', status:'ACTIVE', sev:'MEDIUM',
    objective:'Manual journal above the minimum amount with blank, null, or generic DESCRIPTION field.',
    algorithm:`IF (MANUAL AND amount >= min AND DESCRIPTION in generic list)\nTHEN severity = 'MEDIUM'`,
    impact:'Cannot be assessed for business purpose during an audit.',
    configField:'blankDescMinAmount', configLabel:'Minimum amount for blank description flag', configSuffix:'BHD',
    configHint:'Only flag blank descriptions on entries at or above this value' },
  { id:'CWIP-01', label:'CWIP Ageing — Capitalisation Overdue', status:'ACTIVE', sev:'HIGH',
    objective:'CWIP debit entry older than the configured ageing threshold with no transfer to a fixed asset account.',
    algorithm:`IF (account IN CWIP AND age > cwipAgeingDays) THEN severity = 'HIGH'`,
    impact:'CWIP assets avoid depreciation, overstating profits. IAS 16 requires capitalisation when ready for use.',
    configField:'cwipAgeingDays', configLabel:'CWIP ageing limit', configSuffix:'days',
    configHint:'CWIP entries older than this are flagged for capitalisation review' },
  { id:'CWIP-02', label:'CWIP Below Capitalisation Threshold', status:'ACTIVE', sev:'MEDIUM',
    objective:'Entry to CWIP account where the amount is below the configured capitalisation threshold.',
    algorithm:`IF (account IN CWIP AND 0 < amount < threshold) THEN severity = 'MEDIUM'`,
    impact:'Opex/capex misclassification understates period expenses and overstates assets.',
    configField:'capitalizationThreshold', configLabel:'Capitalisation threshold', configSuffix:'BHD',
    configHint:'CWIP entries below this value should have been expensed' },
];
